spring:
  application:
    name: LumiereBackend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000

lumiere:
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration-ms: 900000 # 15 minutes
      refresh-expiration-ms: 604800000 # 7 days
  razorpay:
    key-id: ${RAZORPAY_KEY_ID}
    key-secret: ${RAZORPAY_KEY_SECRET}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
  frontend:
    url: ${FRONTEND_URL}
  resend:
    api-key: ${RESEND_API_KEY}
    from-email: ${RESEND_FROM_EMAIL}

server:
  port: ${PORT:8080}
